modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Licious17/PixelSeasons/issues"

[[mods]]
modId="pixelseasons"
version="1.0.0"
displayName="PixelSeasons"
displayURL="https://github.com/Licious17/PixelSeasons"
logoFile= "icon.png"
credits="Raid Shadow Legends for sponsoring this project."
authors="Licious, Lileep"
description='''
An addon for the Pixelmon mod that adds compatibility with SereneSeasons.
'''

[[dependencies.pixelseasons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelseasons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelseasons]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.7,)"
    ordering="NONE"
    side="BOTH"
